---
title: "Publications"
---

**Peer-Reviewed Books**

2019\. Bauerle Danzman, Sarah. Merging Interests: When Domestic Firms Shape FDI Policy. Cambridge University Press.[Link](https://www.cambridge.org/core/books/merging-interests/EDAC74C21BBD12A8CAA37CADB7D57F97)

-   Reviewed in Perspective on Politics

-   Book Panel at 2022 APSA – Discussants included Jeffry Frieden, Erica Owen & Patrick Egan

**Refereed Journal Articles**

2025\. “Securitized Political Economy.” European Journal of International Relations. forthcoming. [Link](https://drive.google.com/file/d/1dix2jBfp2nBNZ3enbliOPWcrokj1ZdR0/view?usp=share_link)

2025\. “Competing to Lose: FDI, Investment Incentives, and Taxation Capacity under Fiscal Federalism” (with Alexander Slaski) Business and Politics. forthcoming. [Link](https://drive.google.com/file/d/1YQeJcQeq9i3vjOFd_q2xXEapjDSJtCjG/view?usp=share_link)

2025\. “A Tool is Not a Strategy: Technology Security Amidst Contested Global Orders” Journal of International Economic Law. jgaf019, https://doi.org/10.1093/jiel/jgaf019 [Link](https://drive.google.com/file/d/1XKVn4VVTVdnZW1L04lmrLBghWHyZYDok/view?usp=share_link)

2024\. “Outbound Investment Control: A New Security Tool for the European Union?” (with Sophie Meunier) Columbia FDI Perspectives. No. 398 December 9. [Link](https://ccsi.columbia.edu/sites/ccsi.columbia.edu/files/content/docs/fdi%20perspectives/No%20398%20-%20Meunier%20and%20Bauerle%20Danzman%20-%20FINAL.pdf)

2024\. “The EU’s Geoeconomic Turn: From Policy Laggard to Institutional Innovator” (with Sophie Meunier) Journal of Common Market Studies. 62(4): 1097-1115. [Link](https://drive.google.com/file/d/1CojY3Uflrk_Q0vqgCvV5F0tGBO3fOzU6/view?usp=share_link)

2023\. “Naïve No More: Foreign Direct Investment Screening in the European Union” (with Sophie Meunier) Global Policy. 14: 40-53. [Link](https://doi.org/10.1111/1758-5899.13215) **Recognized as one of the top 10 most cited Global Policy articles published in 2023.**

2023\. "If You Can’t Beat Them, Join Them: The Rise of Investment Screening in Europe in Comparative Perspective." (with Sophie Meunier) Revue des Affairs Européennes. 4: 649-659. [Link](https://drive.google.com/file/d/1yJjq_rARnFGSmd0MpiUxqeCBXH3cqsby/view?usp=share_link)

2023\. “Mapping the Characteristics of Foreign Investment Screening Mechanisms: The New PRISM Dataset” (with Sophie Meunier) International Studies Quarterly. 67(2) https://doi.org/10.1093/isq/sqad026 [Link](https://drive.google.com/file/d/12oJvcKKno_ESExql8gvMw_ecKuaITeho/view?usp=share_link)

2022\. “Explaining Deference: Why and When do Policymakers think FDI needs Tax Incentives?” (with Alexander Slaski) Review of International Political Economy. 29(4): 1085-1111. https://doi.org/10.1080/09692290.2021.1885475 [Link](https://drive.google.com/file/d/1hsIb23Y5yy7RiXWqCY8DEJCIWk_bb4Gg/view?usp=share_link)

2022\. “Incentivizing Embedded Investment: Evidence from Patterns of Foreign Direct Investment in Latin America” (with Alexander Slaski) Review of International Organizations. 17(1):63-87. [Link](https://drive.google.com/file/d/1LFa0CWnLS3SThq-Vo7pM1TOCggflt_6j/view?usp=share_link)

2020\. Bauerle Danzman, Sarah. “Foreign Direct Investment Policy, Domestic Firms, and Financial Constraints.” Business and Politics. 22(2): 279–306. doi:10.1017/bap.2019.13 [Link](https://drive.google.com/file/d/1VARyACdRryMJA70_ASbeVfg1l1iWUVDu/view?usp=share_link) **Winner of the 2020 David P. Baron Award for the best article published in Business and Politics in 2020**

2017\. Bauerle Danzman, Sarah, Thomas Oatley, and William Kindred Winecoff. “All Crises are Global: Capital Cycles in an Imbalanced International Political Economy.” International Studies Quarterly. 61(4): 907–923. [Link](https://drive.google.com/file/d/1XJLPx7qfRni1XqAFF1nUa7UWAn-k6Vqw/view?usp=share_link)

2016\. Bauerle Danzman, Sarah. “Contracting with Whom? The Differential Effects of BITs on Mitigating Sources of Investment Risk.” International Interactions 42(3): 432–478. [Link](https://drive.google.com/file/d/15187nhHAUddboLpTGE_SzRdcyMHvtz3X/view?usp=share_link)

2013\. Oatley, Thomas, William Kindred Winecoff, Sarah Bauerle Danzman, and Andrew Pennock. “The Political Economy of Global Finance: A Network Model” Perspectives on Politics 11(1): 131–151. [Link](https://drive.google.com/file/d/1xYzfmt65a9rK9IEbcfcRF9opUMhBx7r_/view?usp=share_link)

**Book Chapters**

2023\. Bauerle Danzman, Sarah and Gabriella Couloubaritsis. “Balancing Risks: Investment Screening Mechanisms, Essential Security Definitions, and Standards of Evidence” in Weaponising Investments: Volume 1, edited by Jens Hillebrand Pohl, Joanna Warchol, Thomas Papadopoulos, and Janosch Wiesenthal. Springer Studies in Law and Geoeconomics, pp. 1-16.

2022\. Bauerle Danzman, Sarah. “Is FDI at a Critical Juncture? Contemplating a Post-COVID Investment Environment” in Yearbook on International Investment Law and Policy 2020, edited by Lisa Laches, Lise Johnson, and Jesse Coleman. Oxford University Press, pp. 5-18.

2021\. Bauerle Danzman, Sarah. “Investment Screening in the Shadow of Weaponized Interdependence” in The Uses and Abuses of Weaponized Interdependence, edited by Daniel Drezner, Henry Farrell, and Abraham Newman. Washington, D.C.: Brookings, pp. 257-272.

2020\. Bauerle Danzman, Sarah and Geoffrey Gertz. “Facilitating Sustainable Investment: The Role and Limits of Investment Promotion Agencies.” in International Trade, Investment, and the Sustainable Development Goals edited by Cosimo Beverelli, Jurgen Kurtz, and Damian Raess. Cambridge, UK: Cambridge University Press, pp. 140-174.

2019\. Bauerle Danzman, Sarah. “The Political Economy of Bilateral Investment Treaties: The Conditional Effects of BITs on FDI Flows and Domestic Politics.” in Research Handbook on Foreign Direct Investment, edited by Markus Krajewski. Cheltenham, UK: Edward Elgar Publishing, pp. 11-38.

**Business Cases**

2022\. Friedman, Jeremy, Sarah Bauerle Danzman, David Lane. TikTok and National Security: Investment in an Age of Data Sovereignty? HBS No. N9-722-020. Boston, MA: Harvard Business School Publishing.

**Book Reviews**

2021\. Bauerle Danzman, Sarah, “Introduction: Integrating Extractive Resource Politics into Broader International Political Economy.” Review Symposium of Power Grab: Political Survival through Extractive Resource Nationalization (Cambridge University Press) by Paasha Mahdavi. Texas National Security Review.

**Congressional and Government Testimony**

2025\. “Ensuring Investment Security is Narrow, Rigorous, and Fair.” Testimony before the House Committee on Financial Services Subcommittee on National Security Illicit Finance, and International Financial Services, 16 July.

2024\. “Outbound Investment from the United States to China.” Invited Written Testimony for the US-China Economic and Security Review Commission, 23 May.

2023\. “Private Funds/Markets and Outbound Investments in Countries of Concern,” Testimony before the U.S. Securities and Exchange Commission Investor Advisory Committee, 22 June.

2022\. “Toward a Balanced Outbound Investment Screening Regime” Testimony before the Senate Committee on Banking, Housing, and Urban Affairs, 29 September.

**Articles and Policy Papers (Non-Peer Reviewed)**

2024\. Bauerle Danzman, Sarah. Sharing the Post Carbon Economy Means Building a Resilient EV Supply Chain. Atlantic Council. September. https://www.atlanticcouncil.org/in-depth-research-reports/report/sharing-the-post-carbon-economy-means-building-a-resilient-ev-supply-chain/

2023\. Bauerle Danzman, Sarah. Shaping Investment Security Policy: A Guide for Business Associations. Center for Private Investment and Enterprise. May. https://www.cipe.org/resources/shaping-investment-security-policy-a-guide-for-business-associations/

2022\. Bauerle Danzman, Sarah and Emily Kilcrease. “The Illusion of Controls: Unilateral Attempts to Contain China’s Technology Ambitions Will Fail” Foreign Affairs 30 December. https://www.foreignaffairs.com/united-states/illusion-controls

2022\. Bauerle Danzman, Sarah and Emily Kilcrease. Sand in the Silicon: Designing an Outbound Investment Controls Mechanism. Atlantic Council and CNAS Issue Brief. September.

2021\. Bauerle Danzman, Sarah. “National Security, Investment Review, and Sensitive Data.” Proceedings of the American Society of International Law 2021, doi:10.1017/amp.2021.103 2017 Bauerle Danzman, Sarah. “Leveraging WAIPA to Facilitate Private Sector Linkages.” World Association of Investment Promotion Agencies Research Note April. (1658 words)

2016\. Bauerle Danzman, Sarah, Jacqueline Bauman, Michael Holmberg, Jonathan Hreha, Karis Neufeld, Anna Piskunova, Alec Resch, Jamie Spitz, Jocelyn Wallace, and Anna Williams. “Incentivizing an Increasingly Automated Manufacturing Sector: A Descriptive Analysis of U.S. States’ Manufacturing Investment Promotion Programs” Smart Incentives Policy Report December, pp. 1-20.

**Technical Comments on Government Proposed Regulation**

2024\. Comments on Provisions Pertaining to U.S. Investment in Certain National Security Technologies and Products in Countries of Concern. (With Emily Kilcrease, Geoffrey Gertz, Tim Fist, and Ngor Luong) August. (Comments on Proposed Rule)

2023\. Comments on Provisions Pertaining to U.S. Investment in Certain National Security Technologies and Products in Countries of Concern. (With Emily Kilcrease, Tim Fist, Ngor Luong, and Emily Weinstein) September. (Comments on Advanced Notice of Proposed Rulemaking)
