---
title: "Scholarship"
page-layout: article
toc: true
toc-location: right
toc-depth: 2
toc-title: "On this page"
---

My research builds from political science training as an international relations scholar. I am primarily interested in multinational enterprises (MNEs) as domestic and transnational political actors; the relative power of MNEs, local interest groups, and the state; how MNEs shape ideas about the social purpose of political authority; and the implications of multinational production and ownership structures on the security, prosperity, and rights of people. While my early work focuses mostly on questions related to development, my current interests emphasize the intersection of (national) security and economic policy – especially investment regulations. I was trained as a quantitative social scientist, though my scholarship has become increasingly multi-method over time. My research focuses on international political economy, foreign investment screening, and innovation economies. I examine how states balance economic openness with national security concerns in an era of great power competition.

## Books

::: research-item
### Merging Interests: When Domestic Firms Shape FDI Policy.

*Cambridge University Press, 2019*

This book examines how large domestic firms push to liberalize foreign direct investment (FDI) policies to ameliorate financing constraints, often to the detriment of smaller competitors. 

[Publisher](https://www.cambridge.org/core/books/merging-interests/EDAC74C21BBD12A8CAA37CADB7D57F97#fndtn-information) \| [Amazon](https://www.amazon.com/Merging-Interests-Domestic-Policy-Business/dp/1108494145)
:::

## Peer-Reviewed Articles

::: research-item
### [Securitized Political Economy](https://doi.org/10.1177/13540661251364402)

**Sarah Bauerle Danzman.** 2025. *European Journal of International Relations*, forthcoming.

In recent years, many advanced economies have implemented restrictions on cross-border economic activity for national security purposes. The seeming lack of an effective counter lobby against these regulations is puzzling, especially since previous theory and empirical analysis suggests the largest, most globally engaged firms are the best positioned to influence economic policymaking. I develop a theoretical framework to explain firms’ political behavior when economic policy has become “securitized,” meaning that policy entrepreneurs have successfully framed economic regulation as essential for national security. When firms face highly securitized regulatory proposals, they are less able to organize effective opposition. I use a recent case of foreign direct investment (FDI) regulation in the United States to probe and refine the theory’s plausibility. Politicians successfully framed regulation as a national security imperative in a way that limited the business community’s ability to launch public opposition campaigns. Firms responded by either strategically disengaging or using quieter influence tactics that relied on associational groupings. My theory and findings explain why global firms have been largely unable to arrest a substantial and rapid reshaping of the post-war prevailing economic order. These results have broad implications for the domestic and transnational political power of global business in an era of increased geoeconomic competition and raise important questions about how securitized economic landscapes may further erode democratic institutions.

[<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman-2025-SPE.pdf){.btn .btn-sm .btn-outline-secondary} \| [<i class="ai ai-zotero"></i> Save to Reference Manager](https://doi.org/10.1177/13540661251364402){.btn .btn-sm .btn-outline-secondary}
:::

::: research-item
### [Competing to Lose: FDI, Investment Incentives, and Taxation Capacity under Fiscal Federalism](https://doi.org/10.1017/bap.2025.10014)

Alexander Slaski and **Sarah Bauerle Danzman**. 2025. *Business and Politics*, forthcoming.

This article examines how subnational fiscal competition over foreign direct investment affects both the siting of new projects and the ability of local governments to raise tax revenue for social spending. We leverage a quasi-natural experiment, an unexpected declaration by the Brazilian Supreme Court in 2017 that reduced states’ ability to offer investors differentiated tax subsidies. Our results show that disadvantaged regions did not see a major shift in investment patterns after the change in investment law. We do not find a consistent relationship between the incentive law change and state revenue generation, but we do find that incentives are associated with less revenue. The results are consistent with arguments that investment incentives exacerbate inequality by reducing states’ capacity to collect revenue while doing little to affect investment location. Our results illustrate that economic agglomeration is difficult to reverse through tax policy and that fiscal federalism often cannot provide strong enough inducements to drive investment into less advantaged regions.

[<i class="fas fa-globe"></i> PDF](Articles\Slaski_and_Bauerle_Danzman-2025-Competing_to_Lose.pdf){.btn .btn-sm .btn-outline-secondary} \| [<i class="ai ai-zotero"></i> Save to Reference Manager](https://doi.org/10.1017/bap.2025.10014){.btn .btn-sm .btn-outline-secondary}
:::

::: research-item
### [A Tool is Not a Strategy: Technology Security Amidst Contested Global Orders](https://doi.org/10.1093/jiel/jgaf019)

**Sarah Bauerle Danzman.** 2025. *Journal of International Economic Law*, 28(2):302-313.

In recent years, policymakers and analysts concerned for the future of global economic governance have advanced numerous proposals to constrain governments’ use of security exceptions. However, framing the current situation merely as a governance crisis may create an illusion that consensus still exists regarding the fundamental principles that should govern global economic relations. To understand whether and how the current Trump administration wishes to change the global economic order—and whether and how it may succeed—we must concentrate analytic attention beyond the tools of the administration and instead examine the objectives these tools are being placed in service of. I examine the strategic objectives of the three most recent US administrations related to international investment and trade in dual-use technology, as well as the ways in which each administration has employed, sharpened, and strengthened similar tools in service of different visions of global governance and order. I conclude by demonstrating how Trump 2.0, in contrast to Trump 1.0 and the Biden administration, is more fully challenging core principles of mutually beneficial exchange in ways that are order breaking.

[<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman-2025-Tool_Is_Not_A_Strategy.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### [Outbound Investment Control: A New Security Tool for the European Union](https://ccsi.columbia.edu/sites/ccsi.columbia.edu/files/content/docs/fdi%20perspectives/No%20398%20-%20Meunier%20and%20Bauerle%20Danzman%20-%20FINAL.pdf)

Sophie Meunier and **Sarah Bauerle Danzman.** 2024. *Columbia FDI Perspectives*, No. 398.

[<i class="fas fa-globe"></i> PDF](Articles\Meunier_Bauerle_Danzman-2024-Outbound_FDI-Control.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### [The EU’s Geoeconomic Turn: From Policy Laggard to Institutional Innovator](https://doi.org/10.1111/jcms.13599)

**Sarah Bauerle Danzman** and Sophie Meunier. 2024. *Journal of Common Market Studies*, 62(4):1097-1115.

Heightened geopolitical tensions and the growing securitization of economic exchange over the past decade have prompted many countries to adopt new geoeconomic tools. Long resistant to this geoeconomic turn, the European Union (EU) has since 2017 created a panoply of innovative policy tools that blend trade and investment with essential security concerns. This article asks why and how the EU has been able to operate the doctrinal and policy changes necessary to put economic tools at the service of geopolitics. After introducing a typology of the defensive and offensive geoeconomic tools deployed by advanced industrial economies, we present the novel geoeconomic toolkit quickly assembled by the EU, which we explain by the confluence of external factors that triggered European leaders' beliefs that change was necessary and internal factors that made such change institutionally and politically possible, a trend reinforced by the pandemic and the Russian invasion of Ukraine.

[<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman_Meunier-2024-Geoeconomic_Turn.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### [Naïve No More: Foreign Direct Investment Screening in the European Union](https://doi.org/10.1111/1758-5899.13215)

**Sarah Bauerle Danzman** and Sophie Meunier. 2023. *Global Policy*, 14(S3):40-53.

This paper asks what explains the creation and comparative features of national Investment Screening Mechanisms (ISMs) in Europe. After providing a brief history and definition of ISMs, we provide descriptive patterns about the similarities and differences in the investment screening features of national ISMs in EU member states. We then explain differences in national screening policies by focusing on the role of public debt, Chinese investment, R&D expenditures and various geographic groupings. Finally, we make three policy arguments about the rise of ISMs in Europe: (1) ISMs have not been designed as protectionist instruments, (2) the politics of inward investment screening reflects a shift from economic to security logic in addressing the fundamental tension between the benefits and vulnerabilities of open markets and (3) the EU can use the ‘commercialisation’ of security to extend its own competence in the security sphere. We conclude by considering how the rapid expansion of investment screening in Europe could affect economic openness, as well as the role of the EU as a global actor.

[<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman_Meunier_2023_Naive_No_More.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### If You Can’t Beat Them, Join Them: The Rise of Investment Screening in Europe in Comparative Perspective

**Sarah Bauerle Danzman** and Sophie Meunier. 2023. *Revue des Affairs Européennes*, 4:646-659.

Investment screening, the process by which national governments review whether particular foreign
investment transactions generate risks to essential security, is finally having a moment in Europe.
Since the European Union (EU) created its own investment screening framework in 2019, almost all
Member States have reinforced, adopted, or discussed adopting a national Investment Screening
Mechanism (ISM). European countries are thereby joining the growing list of advanced industrial
democracies on other continents with robust investment screening regulations and practice.
This article analyzes the growth of investment screening in Europe in a broader global context. First,
we show how recent policy developments in Europe fit with the way governments regulate inward
foreign direct investment (FDI) in other countries. Then we highlight global patterns in investment
screening regulations. Third, we explain these recent developments worldwide by focusing on three
factors: the rise of China as an outward investor, technological change expanding the security
implications of most goods and services, and the diffusion of investment screening norms. Finally,
we reflect on the consequences of this recent expansion of investment screening.

[<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman_Meunier-2023-Join_Them.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### [Mapping the Characteristics of Foreign Investment Screening Mechanisms: The New PRISM Dataset](https://doi.org/10.1093/isq/sqad026)

**Sarah Bauerle Danzman** and Sophie Meunier. 2023. *International Studies Quarterly*, 67(2):sqad026.

Since the 2008 financial crisis, many advanced industrialized economies, while eager to attract foreign direct investment (FDI), have also implemented or tightened investment screening mechanisms (ISMs), which empower governments to restrict foreign takeovers. ISMs, at the nexus between international political economy and international security, are an understudied phenomenon, although they have recently gained in policy prominence worldwide as a result of emerging technological risks and new threat actors. This research note introduces the Politics and Regulation of Investment Screening Mechanisms dataset, a newly coded dataset on ISMs in Organisation for Economic Co-operation and Development (OECD) countries from 2007 to 2021, examining the evolution of seven key features of investment screening over time. Based on these novel data, we then describe patterns in the evolution of foreign investment screening policies. Next, we consider likely applications of the dataset to answer questions about the politics of investment as well as broader questions of economic exchange and institutional design in an age of great power competition—including by providing some initial statistical exercises on the relationship between Chinese FDI and R&D spending on ISM features. Finally, we suggest how investment screening fits within the new arsenal of unilateral instruments of economic statecraft currently being developed by liberal democracies.

[<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman_Meunier-2023-PRISM.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### [Explaining Deference: Why and When do Policymakers think FDI needs Tax Incentives?](https://doi.org/10.1080/09692290.2021.1885475)

**Sarah Bauerle Danzman** and Alexander Slaski. 2022. *Review of International Political Economy*, 29(4): 1085-1111.

Why do governments compete for investment through tax incentives when there is strong evidence that such packages are inconsequential to the locational decisions of foreign firms? Previous scholarship has attributed pro-business policies such as investment incentives to factors including the structural power of business in an era of international capital mobility, fiscal competition generated through political decentralization or electoral pandering by political leaders. However, there is currently little understanding about how individuals, in their role as decision-makers within government agencies, form beliefs over how to best attract investment. Building on insights from the bureaucratic politics and behavioral economics literatures, we anticipate investment promotion professionals are more likely to view investment incentives as effective attraction tools when they have limited previous experience in the private sector, when they work for investment promotion agencies that are more integrated into the national bureaucracy, and when employee performance is evaluated based on deals closed. We test these expectations with a conjoint survey experiment of investment promotion professionals designed to uncover respondents’ beliefs over the relative importance of different components of the investment environment to firms’ locational decisions, and find substantial support for our expectations.

[<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman_Slaski-2022-RIPE.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### [Incentivizing Embedded Investment: Evidence from Patterns of Foreign Direct Investment in Latin America](https://doi.org/10.1007/s11558-021-09418-0)

**Sarah Bauerle Danzman** and Alexander Slaski. 2022. *Review of International Organizations*, 17(2022): 63-87.

Governments frequently offer tax incentives to induce localized investments. This is puzzling because previous research finds tax incentives are rarely decisive factors in firms’ locational decision-making. Some argue incentives reflect hyper capital mobility, which strengthens multinational enterprises’ bargaining leverage vis-à-vis governments that wish to attract investment. Others emphasize the domestic political institutions and electoral considerations that incentivize politicians to publicly court investors. We argue that firms’ leverage over governments stems from investment characteristics associated with governments’ broader development objectives. We test our argument on deal-level data on investment incentives in Latin America from 2010 to 2017. Our results indicate firms are more likely to receive incentives when they are already embedded in local markets and when they exhibit characteristics associated with low ex post mobility. These results challenge widely held beliefs over what provides firms political power in an age of globalization, and suggest that governments use incentives primarily to fulfill their economic and political objectives rather than because globalization destroys states’ capacity to tax mobile capital.

[<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman_Slaski-2022-RIO.pdf){.btn .btn-sm .btn-outline-secondary}
:::

::: research-item
### [Foreign Direct Investment Policy, Domestic Firms, and Financial Constraints](https://doi:10.1017/bap.2019.13)

**Sarah Bauerle Danzman.** 2020. *Business and Politics*, 22(2): 279-306.

The past three decades have witnessed a spectacular evolution in policies toward foreign direct investment (FDI). Whose interests do these policy innovations reflect? While existing theory suggests popular pressure drives openness, I argue reforms occur when shifts in financial access change local economic elites’ policy preferences toward FDI. When large domestic firms no longer have access to cheap credit through political connections, liquidity constraints outweigh firms' preferences to exclude foreigners. Economic elites then pressure governments to pursue liberal FDI policy environments. Using a combination of measures of FDI policy for up to 166 countries from 1973–2015, I find increases in financial constraints are robustly associated with decreases in foreign equity restrictions, and this relationship is strongest when domestic political institutions favor business interests. A financing constraints explanation of FDI policy reform has important implications for explanations of policy change, theories of business power amid increased interdependence, and expectations over the distributive effects of globalization.

[<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman-2020.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### [All Crises are Global: Capital Cycles in an Imbalanced International Political Economy](https://doi.org/10.1093/isq/sqx054)

**Sarah Bauerle Danzman,** W. Kindred Winecoff, and Thomas Oatley 2017. *International Studies Quarterly*, 61(4): 907-923.

What factors generate financial fragility in open economies? Existing research assumes that the development of these conditions is more likely to emerge under some configurations of domestic economic and political attributes. We examine the development of financial fragility through the ontological lens of the new interdependence approach, which assumes that global factors can be as important as local factors in generating outcomes. We analyze global financial conditions from 1978 to 2009 and argue that contemporary global finance is an oscillating system that generates boom and bust capital flow cycles. The phases of this cycle are a consequence of the scale of US net borrowing on global markets: when the United States is a large net importer of foreign capital, other economies struggle to attract foreign capital and are substantially less likely to develop fragile financial positions; when US net capital imports fall, other economies receive an abundance of foreign capital, and financial fragility becomes more likely. In contrast, we find little evidence that cross-national variation in political institutions or financial systems explains why fragility develops, although some regional interdependencies are evident. We conclude that global conditions drive the probability of crises occurring someplace in the system, while local outcomes appear to be idiosyncratic.

[<i class="fas fa-globe"></i> PDF](Articles\BDOW-2017.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### [Contracting with Whom? The Differential Effects of BITs on Mitigating Sources of Investment Risk](https://doi.org/10.1080/03050629.2016.1121451)

**Sarah Bauerle Danzman.** 2016. *International Interactions*, 42(3): 452-478.

Under what conditions can governments use international commitments such as Bilateral Investment Treaties (BITs) to attract foreign direct investment (FDI)? Although numerous studies have attempted to answer this question, none considers how investment treaties may have heterogeneous affects across industry. I argue BIT effect is strongest when the obsolescing bargaining problem between firms and governments is most protracted, namely, when FDI relies on strong contracts between firms and states. Using a time series cross-sectional data set of 114 developing countries from 1985 to 2011, I find BITs are associated with increases in infrastructure investment, an industry particularly reliant on the sanctity of government contracts, but not with total FDI inflows. Moreover, BITs with strong arbitration provisions display the strongest statistical effect on infrastructure investment, while BITs that do not provide investors with such protections are not associated with increased investment. My results have implications for both scholarship on the relationship between governments and multinational firms as well as for the study of international institutions more broadly. To properly ascertain the effects of international treaties and institutions, scholars should consider not just whether institutions constrain or inform—or matter at all—but also the extent to which the targets of institutions have heterogeneous responses to them.

[<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman-2016.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### [The Political Economy of Global Finance: A Network Model](https://doi:10.1017/S1537592712003593)

Thomas Oatley, W.Kindred Winecoff, Andrew Pennock, and **Sarah Bauerle Danzman.** 2013. *Perspectives on Politics*, 11(1):133-153.

Although the subprime crisis regenerated interest in and stimulated debate about how to study the politics of global finance, it has not sparked the development of new approaches to International Political Economy (IPE), which remains firmly rooted in actor-centered models. We develop an alternative network-based approach that shifts the analytical focus to the relations between actors. We first depict the contemporary global financial system as a network, with a particular focus on its hierarchical structure. We then explore key characteristics of this global financial network, including how the hierarchic network structure shapes the dynamics of financial contagion and the source and persistence of power. Throughout, we strive to relate existing research to our network approach in order to highlight exactly where this approach accommodates, where it extends, and where it challenges existing knowledge generated by actor-centered models. We conclude by suggesting that a network approach enables us to construct a systemic IPE that is theoretically and empirically pluralist.

[<i class="fas fa-globe"></i> PDF](Articles\Oatley_et_al-2013.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

## Book Chapters

::: research-item
### Balancing Risks: Investment Screening Mechanisms, Essential Security Definitions, and Standards of Evidence

**Sarah Bauerle Danzman** and Gabriella Couloubaritsis. In *Weaponising Investments: Volume 1*, edited by Jens Hillebrand Pohl, Joanna Warchol, Thomas Papadopoulos, and Janosch Wiesenthal, 1-16. Springer Studies in Law and Geoeconomics, 2023.

As governments reach more toward essential security exceptions to govern their economic regulatory environment, definitions of national security and related concepts become increasingly consequential. Most OECD countries now have investment screening mechanisms (ISMs) to review inward investment for potential security concerns, but there remains substantial variation in how essential security is delineated and the standards of evidence required to mitigate or block a transaction. This article advances the literature in four ways. First, it provides a descriptive overview of how countries’ ISMs conceptualize investment security, creating a typology of country risk profiles. Second, it develops an explanation for why countries systematically vary in their approach to security risks. Third, it uses the case of Germany to discuss how dynamics around critical technologies are pushing some countries to decrease their standards of evidence requirements. Finally, it discusses the implications of countries’ security concepts for economic outcomes.

[<i class="fas fa-book"></i> Publisher](https://link.springer.com/book/10.1007/978-3-031-41475-6){.btn .btn-sm .btn-outline-secondary}\| [<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman_Couloubaritsis-2023.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### Is FDI at a Critical Juncture? Contemplating a Post-COVID Investment Environment

**Sarah Bauerle Danzman**. In *Yearbook on International Investment Law and Policy 2020*, edited by Lisa Sachs, Lise Johnson, and Jesse Coleman, 5-18. Oxford University Press, 2022.

[<i class="fas fa-book"></i> Publisher](https://global.oup.com/academic/product/yearbook-on-international-investment-law-and-policy-2020-9780192862334?cc=us&lang=en& ){.btn .btn-sm .btn-outline-secondary} \| [<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman_2022_Yearbook.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### Investment Screening in the Shadow of Weaponized Interdependence

**Sarah Bauerle Danzman**. In *The Uses and Abuses of Weaponized Interdependence*, edited by Daniel Drezner, Henry Farrell, and Abraham Newman, 257-272. Brookings Press, 2021.

[<i class="fas fa-book"></i> Publisher](https://www.brookings.edu/books/the-uses-and-abuses-of-weaponized-interdependence/){.btn .btn-sm .btn-outline-secondary}\| [<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman-2021-WIBook.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### Investment Screening in the Shadow of Weaponized Interdependence

**Sarah Bauerle Danzman**. In *The Uses and Abuses of Weaponized Interdependence*, edited by Daniel Drezner, Henry Farrell, and Abraham Newman, 257-272. Brookings Press, 2021.

[<i class="fas fa-book"></i> Publisher](https://www.brookings.edu/books/the-uses-and-abuses-of-weaponized-interdependence/){.btn .btn-sm .btn-outline-secondary}\| [<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman-2021-WIBook.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### Facilitating Sustainable Investment: The Role and Limits of Investment Promotion Agencies

**Sarah Bauerle Danzman** and Geoffrey Gertz. In *International Trade, Investment, and the Sustainable Development Goals,*, edited by Cosimo Beverelli, Jurgen Kurtz, and Damian Raess, 140-174. Cambridge University Press, 2020.

[<i class="fas fa-book"></i> Publisher](https://www.cambridge.org/core/books/international-trade-investment-and-the-sustainable-development-goals/F18E76BE53B84192F65EF37E3407B627){.btn .btn-sm .btn-outline-secondary}\| [<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman_Gertz-2020-IPAs.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

::: research-item
### The Political Economy of Bilateral Investment Treaties: The Conditional Effects of BITs on FDI Flows and Domestic Politics

**Sarah Bauerle Danzman**. In *Research Handbook on Foreign Direct Investment,*, edited by Markus Krajewski and Rhea T. Hoffman, 11-38. Edward Elgar Publishing, 2019.

[<i class="fas fa-book"></i> Publisher](https://www.elgaronline.com/edcollbook/edcoll/9781785369841/9781785369841.xml){.btn .btn-sm .btn-outline-secondary}\| [<i class="fas fa-globe"></i> PDF](Articles\Bauerle_Danzman-2019-BIT_Handbook.pdf){.btn .btn-sm .btn-outline-secondary} 
:::

## Other Writing

::: research-item
### [TikTok and National Security: Investment in an Age of Data Sovereignty?](https://www.hbs.edu/faculty/Pages/item.aspx?num=62354)

Jeremy Friedman, **Sarah Bauerle Danzman**, and David Lane. *Harvard Business School Publishing*, HBS No. N9-722-020, 2022.

:::

::: research-item
### [Introduction: Integrating Extractive Resource Politics into Broader International Political Economy](https://tnsr.org/roundtable/book-review-roundtable-nationalizing-natural-resources/)

**Sarah Bauerle Danzman**. 2021. *Texas National Security Review*, Review Symposium of Power Grab: Political Survival through Extractive Resource Nationalization (Cambridge University Press) by Paasha Mahdavi.

:::

